services:
  postgres:
    image: timescale/timescaledb:2.26.4-pg18
    container_name: cloudpulse-postgres
    environment:
      POSTGRES_DB: cloudpulse
      POSTGRES_USER: cloudpulse
      POSTGRES_PASSWORD: cloudpulse
    volumes:
      - postgres_data:/var/lib/postgresql
    network_mode: host
    restart: unless-stopped
    mem_limit: 1g
    cpus: "1.0"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudpulse -d cloudpulse"]
      interval: 10s
      timeout: 5s
      retries: 10

  cloudpulse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudpulse
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    cpus: "1.0"
    environment:
      - CLOUDPULSE_HTTP_ADDRESS
      - CLOUDPULSE_HTTP_PORT
    volumes:
      - ./configs:/app/configs:ro
    command: ["-config", "/app/configs/config.yaml"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: cloudpulse-prometheus
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 64M

  grafana:
    image: grafana/grafana:13.0.1
    container_name: cloudpulse-grafana
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    environment:
      GF_PLUGINS_PREINSTALL_SYNC: "yesoreyeram-infinity-datasource"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 64M

volumes:
  postgres_data:
