apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: 127.0.0.1:5432
    database: cloudpulse
    user: cloudpulse
    secureJsonData:
      password: cloudpulse
    jsonData:
      sslmode: "disable"
      postgresVersion: 16
      timescaledb: true
