// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "CloudPulse Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analytics/anomalies": {
            "get": {
                "description": "Analyses cost data over a time range and returns any detected anomalies with severity, z-score, and deviation metrics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Detect cost anomalies",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detected anomalies",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Anomaly"
                            }
                        }
                    },
                    "500": {
                        "description": "Detection failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/forecast": {
            "get": {
                "description": "Generates a 7-day cost forecast based on historical data within the specified time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forecasting"
                ],
                "summary": "Get cost forecast",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Forecast data points",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.ForecastPoint"
                            }
                        }
                    },
                    "500": {
                        "description": "Forecast generation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/summary": {
            "get": {
                "description": "Returns aggregated cost data over a time range, grouped by the specified window (daily, weekly, or monthly).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get cost summary",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "daily",
                            "weekly",
                            "monthly"
                        ],
                        "type": "string",
                        "default": "daily",
                        "description": "Aggregation window: daily, weekly, or monthly.",
                        "name": "window",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cost aggregation results",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.AggregatedCost"
                            }
                        }
                    },
                    "500": {
                        "description": "Aggregation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ingest": {
            "post": {
                "description": "Triggers collection of billing data from all enabled cloud providers for the last 24 hours.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingestion"
                ],
                "summary": "Trigger billing data ingestion",
                "responses": {
                    "202": {
                        "description": "Ingestion completed successfully",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.StatusResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ingestion failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/daily": {
            "get": {
                "description": "Builds a daily cost report including summary, anomalies, and forecast. Optionally delivers via configured webhooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Generate daily report",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "default": "false",
                        "description": "Set to 'true' to send report via webhooks.",
                        "name": "deliver",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daily report",
                        "schema": {
                            "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Report"
                        }
                    },
                    "500": {
                        "description": "Report generation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Webhook delivery failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/monthly": {
            "get": {
                "description": "Builds a monthly cost report including summary, anomalies, and forecast. Optionally delivers via configured webhooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Generate monthly report",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "default": "false",
                        "description": "Set to 'true' to send report via webhooks.",
                        "name": "deliver",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Monthly report",
                        "schema": {
                            "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Report"
                        }
                    },
                    "500": {
                        "description": "Report generation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Webhook delivery failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/weekly": {
            "get": {
                "description": "Builds a weekly cost report including summary, anomalies, and forecast. Optionally delivers via configured webhooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Generate weekly report",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-01-01",
                        "description": "Start date (YYYY-MM-DD). Defaults to 30 days ago.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-01-31",
                        "description": "End date (YYYY-MM-DD). Defaults to today.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "default": "false",
                        "description": "Set to 'true' to send report via webhooks.",
                        "name": "deliver",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Weekly report",
                        "schema": {
                            "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Report"
                        }
                    },
                    "500": {
                        "description": "Report generation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Webhook delivery failed",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns the health status of the CloudPulse API server.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_crypticani_cloudpulse_internal_domain.AggregatedCost": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Provider"
                },
                "service": {
                    "type": "string"
                },
                "total_cost": {
                    "type": "number"
                },
                "window_end": {
                    "type": "string"
                },
                "window_start": {
                    "type": "string"
                }
            }
        },
        "github_com_crypticani_cloudpulse_internal_domain.Anomaly": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "actual": {
                    "type": "number"
                },
                "baseline": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "moving_average_delta": {
                    "type": "number"
                },
                "percent_deviation": {
                    "type": "number"
                },
                "provider": {
                    "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Provider"
                },
                "service": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "z_score": {
                    "type": "number"
                }
            }
        },
        "github_com_crypticani_cloudpulse_internal_domain.ForecastPoint": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "confidence_high": {
                    "type": "number"
                },
                "confidence_low": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "forecast_cost": {
                    "type": "number"
                },
                "provider": {
                    "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Provider"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "github_com_crypticani_cloudpulse_internal_domain.Provider": {
            "type": "string",
            "enum": [
                "aws",
                "azure",
                "gcp",
                "oci"
            ],
            "x-enum-varnames": [
                "ProviderAWS",
                "ProviderAzure",
                "ProviderGCP",
                "ProviderOCI"
            ]
        },
        "github_com_crypticani_cloudpulse_internal_domain.Report": {
            "type": "object",
            "properties": {
                "anomalies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.Anomaly"
                    }
                },
                "forecast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.ForecastPoint"
                    }
                },
                "generated": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                },
                "summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_crypticani_cloudpulse_internal_domain.AggregatedCost"
                    }
                }
            }
        },
        "internal_ports_http.ErrorResponse": {
            "description": "Error response returned when an operation fails.",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "internal_ports_http.StatusResponse": {
            "description": "Generic status response for operations.",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "CloudPulse API",
	Description:      "Multi-cloud FinOps cost analytics platform. Collects billing data from AWS, Azure, GCP, and OCI, normalises it into a canonical schema, and provides real-time cost summaries, anomaly detection, forecasting, and automated reporting.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
